/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controlador;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Cliente;
import model.ClienteFisico;
import model.ClienteJuridico;
import model.Endereco;

/**
 *
 * @author aluno
 */
public class CadastroCliente extends javax.swing.JFrame {

    public CadastroCliente() {
        estilo();
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jtCadastro = new javax.swing.JTabbedPane();
        jpCadastroPessoaFisica = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtNomeFisica = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtEnderecoFisica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtComplementoFisica = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtCepFisica = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtEmailFisica = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtTelefoneFisica = new javax.swing.JTextField();
        jbCadastroFisico = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jtCpfFisico = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtRgFisico = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jtOrgaoEmissorFisico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jtNumeroFisico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtBairroFisico = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jcEstadoFisico = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        jtCelularFisico = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jcSexoFisico = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jtCidadeFisico = new javax.swing.JTextField();
        jcEstadoEmssorFisico = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jbVoltarCadastroFisica = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtObservacaoFisica = new javax.swing.JTextArea();
        jpCadastroPessoaJuridica = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jtNomeJuridico = new javax.swing.JTextField();
        jtEnderecoJuridico = new javax.swing.JTextField();
        jtComplementoJuridico = new javax.swing.JTextField();
        jtCepJuridico = new javax.swing.JTextField();
        jtTelefoneJuridico = new javax.swing.JTextField();
        jtEmailJuridico = new javax.swing.JTextField();
        jbCadastroJuridico = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jtCnpj = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jcEstadoJuridico = new javax.swing.JComboBox<>();
        jtNumeroJuridico = new javax.swing.JTextField();
        jtBairroJuridico = new javax.swing.JTextField();
        jtCidadeJuridico = new javax.swing.JTextField();
        jtCelularJuridico = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jbVoltarCadastroJuridica = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jtNomeResponsavel = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtObservacaoJuridica = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GF-Alarme");
        setPreferredSize(new java.awt.Dimension(650, 500));
        setResizable(false);

        jpCadastroPessoaFisica.setPreferredSize(new java.awt.Dimension(600, 500));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Complemento:");

        jLabel4.setText("CEP:");

        jLabel5.setText("E-mail:");

        jtEmailFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtEmailFisicaActionPerformed(evt);
            }
        });

        jLabel6.setText("Telefone:");

        jbCadastroFisico.setText("Cadastrar");
        jbCadastroFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroFisicoActionPerformed(evt);
            }
        });

        jLabel13.setText("CPF:");

        jLabel16.setText("RG:");

        jLabel17.setText("Orgão Emissor:");

        jLabel18.setText("Estado Emissor");

        jLabel19.setText("Número:");

        jLabel20.setText("Bairro:");

        jLabel21.setText("Estado:");

        jcEstadoFisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RS", "SC", "SE", "SP", "TO" }));

        jLabel22.setText("Celular:");

        jLabel23.setText("sexo:");

        jcSexoFisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));

        jLabel27.setText("Cidade:");

        jtCidadeFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCidadeFisicoActionPerformed(evt);
            }
        });

        jcEstadoEmssorFisico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RS", "SC", "SE", "SP", "TO" }));

        jbVoltarCadastroFisica.setText("Voltar");
        jbVoltarCadastroFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarCadastroFisicaActionPerformed(evt);
            }
        });

        jLabel31.setText("Observação:");

        jtObservacaoFisica.setColumns(20);
        jtObservacaoFisica.setRows(5);
        jScrollPane2.setViewportView(jtObservacaoFisica);

        javax.swing.GroupLayout jpCadastroPessoaFisicaLayout = new javax.swing.GroupLayout(jpCadastroPessoaFisica);
        jpCadastroPessoaFisica.setLayout(jpCadastroPessoaFisicaLayout);
        jpCadastroPessoaFisicaLayout.setHorizontalGroup(
            jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroPessoaFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator6)
                    .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                        .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCpfFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNomeFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtRgFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtOrgaoEmissorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcEstadoEmssorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCepFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEnderecoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNumeroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtComplementoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtBairroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCidadeFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                        .addComponent(jbVoltarCadastroFisica)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCadastroFisico))
                                    .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtTelefoneFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtCelularFisico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEmailFisica, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel31)
                            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcSexoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCadastroPessoaFisicaLayout.setVerticalGroup(
            jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroPessoaFisicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtNomeFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jtCpfFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jtRgFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jtOrgaoEmissorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jcEstadoEmssorFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jcSexoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtCepFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtEnderecoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jtNumeroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtComplementoFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jtBairroFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jtCidadeFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jcEstadoFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtTelefoneFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jtCelularFisico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jtEmailFisica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jpCadastroPessoaFisicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastroFisico)
                    .addComponent(jbVoltarCadastroFisica))
                .addContainerGap())
        );

        jtCadastro.addTab("Cadastro Pessoa Física", jpCadastroPessoaFisica);

        jLabel7.setText("Nome da Empresa:");

        jLabel8.setText("Endereço:");

        jLabel9.setText("Complemento:");

        jLabel10.setText("CEP:");

        jLabel11.setText("E-mail:");

        jLabel12.setText("Telefone:");

        jbCadastroJuridico.setText("Cadastrar");
        jbCadastroJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastroJuridicoActionPerformed(evt);
            }
        });

        jLabel14.setText("CNPJ:");

        jLabel24.setText("Número:");

        jLabel25.setText("Bairro:");

        jLabel26.setText("Cidade:");

        jLabel28.setText("Celular:");

        jLabel29.setText("Estado:");

        jcEstadoJuridico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MG", "MS", "MT", "PA", "PB", "PE", "PI", "PR", "RJ", "RN", "RO", "RS", "SC", "SE", "SP", "TO" }));

        jbVoltarCadastroJuridica.setText("Voltar");
        jbVoltarCadastroJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVoltarCadastroJuridicaActionPerformed(evt);
            }
        });

        jLabel15.setText("Nome do Responsável:");

        jLabel30.setText("Observação:");

        jtObservacaoJuridica.setColumns(20);
        jtObservacaoJuridica.setRows(5);
        jScrollPane1.setViewportView(jtObservacaoJuridica);

        javax.swing.GroupLayout jpCadastroPessoaJuridicaLayout = new javax.swing.GroupLayout(jpCadastroPessoaJuridica);
        jpCadastroPessoaJuridica.setLayout(jpCadastroPessoaJuridicaLayout);
        jpCadastroPessoaJuridicaLayout.setHorizontalGroup(
            jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jbVoltarCadastroJuridica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbCadastroJuridico)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.DEFAULT_SIZE, 710, Short.MAX_VALUE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                        .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtNomeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCepJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEnderecoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel24)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtNumeroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtComplementoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtCidadeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel29)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jcEstadoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtBairroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtTelefoneJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtCelularJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtEmailJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel30))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCadastroPessoaJuridicaLayout.setVerticalGroup(
            jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroPessoaJuridicaLayout.createSequentialGroup()
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jtCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jtNomeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jtNomeResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtEnderecoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jtCepJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jtNumeroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jtComplementoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jtBairroJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jtCidadeJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel29)
                        .addComponent(jcEstadoJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(jtCelularJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jtTelefoneJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jtEmailJuridico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addGroup(jpCadastroPessoaJuridicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastroJuridico)
                    .addComponent(jbVoltarCadastroJuridica))
                .addContainerGap())
        );

        jtCadastro.addTab("Cadastro Pessoa Jurídica", jpCadastroPessoaJuridica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtCadastro)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtEmailFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtEmailFisicaActionPerformed

    }//GEN-LAST:event_jtEmailFisicaActionPerformed

    private void jbVoltarCadastroJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarCadastroJuridicaActionPerformed
        janelaTelaPrincipal();
    }//GEN-LAST:event_jbVoltarCadastroJuridicaActionPerformed

    private void jbVoltarCadastroFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVoltarCadastroFisicaActionPerformed
        janelaTelaPrincipal();
    }//GEN-LAST:event_jbVoltarCadastroFisicaActionPerformed

    private void jtCidadeFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCidadeFisicoActionPerformed

    }//GEN-LAST:event_jtCidadeFisicoActionPerformed

    private void jbCadastroFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroFisicoActionPerformed
        cadastrarPessoaFisica();
    }//GEN-LAST:event_jbCadastroFisicoActionPerformed

    private void jbCadastroJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastroJuridicoActionPerformed
        cadastrarPessoaJuridico();

    }//GEN-LAST:event_jbCadastroJuridicoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jbCadastroFisico;
    private javax.swing.JButton jbCadastroJuridico;
    private javax.swing.JButton jbVoltarCadastroFisica;
    private javax.swing.JButton jbVoltarCadastroJuridica;
    private javax.swing.JComboBox<String> jcEstadoEmssorFisico;
    private javax.swing.JComboBox<String> jcEstadoFisico;
    private javax.swing.JComboBox<String> jcEstadoJuridico;
    private javax.swing.JComboBox<String> jcSexoFisico;
    private javax.swing.JPanel jpCadastroPessoaFisica;
    private javax.swing.JPanel jpCadastroPessoaJuridica;
    private javax.swing.JTextField jtBairroFisico;
    private javax.swing.JTextField jtBairroJuridico;
    private javax.swing.JTabbedPane jtCadastro;
    private javax.swing.JTextField jtCelularFisico;
    private javax.swing.JTextField jtCelularJuridico;
    private javax.swing.JTextField jtCepFisica;
    private javax.swing.JTextField jtCepJuridico;
    private javax.swing.JTextField jtCidadeFisico;
    private javax.swing.JTextField jtCidadeJuridico;
    private javax.swing.JTextField jtCnpj;
    private javax.swing.JTextField jtComplementoFisica;
    private javax.swing.JTextField jtComplementoJuridico;
    private javax.swing.JTextField jtCpfFisico;
    private javax.swing.JTextField jtEmailFisica;
    private javax.swing.JTextField jtEmailJuridico;
    private javax.swing.JTextField jtEnderecoFisica;
    private javax.swing.JTextField jtEnderecoJuridico;
    private javax.swing.JTextField jtNomeFisica;
    private javax.swing.JTextField jtNomeJuridico;
    private javax.swing.JTextField jtNomeResponsavel;
    private javax.swing.JTextField jtNumeroFisico;
    private javax.swing.JTextField jtNumeroJuridico;
    private javax.swing.JTextArea jtObservacaoFisica;
    private javax.swing.JTextArea jtObservacaoJuridica;
    private javax.swing.JTextField jtOrgaoEmissorFisico;
    private javax.swing.JTextField jtRgFisico;
    private javax.swing.JTextField jtTelefoneFisica;
    private javax.swing.JTextField jtTelefoneJuridico;
    // End of variables declaration//GEN-END:variables

    private void estilo() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void janelaTelaPrincipal() {
        TelaPrincipal aux = new TelaPrincipal();
        aux.setVisible(true);
        setVisible(false);
    }

    private void cadastrarPessoaFisica() {
        try {
            String nome = jtNomeFisica.getText();
            String cpf = jtCpfFisico.getText();
            String rg = jtRgFisico.getText();
            String orgaoEmissor = jtOrgaoEmissorFisico.getText();
            String estadoEmissor = (String) jcEstadoEmssorFisico.getSelectedItem();
            String sexo = (String) jcSexoFisico.getSelectedItem();
            String cep = jtCepFisica.getText();
            String rua = jtEnderecoFisica.getText();
            int numero = Integer.parseInt(jtNumeroFisico.getText());
            String complemento = jtComplementoFisica.getText();
            String bairro = jtBairroFisico.getText();
            String cidade = jtCidadeFisico.getText();
            String estado = (String) jcEstadoFisico.getSelectedItem();
            String telefone = jtTelefoneFisica.getText();
            String celular = jtCelularFisico.getText();
            String email = jtEmailFisica.getText();

            if (nome.equals(null) || nome.equals("")
                    || rg.equals(null) || rg.equals("")
                    || orgaoEmissor.equals(null) || orgaoEmissor.equals("")
                    || cep.equals(null) || cep.equals("")
                    || rua.equals(null) || rua.equals("")
                    || numero == 0
                    || complemento.equals(null) || complemento.equals("")
                    || bairro.equals(null) || bairro.equals("")
                    || cidade.equals(null) || cidade.equals("")
                    || telefone.equals(null) || telefone.equals("")
                    || celular.equals(null) || celular.equals("")
                    || email.equals(null) || email.equals("")) {

                semDados();

            } else {
                Cliente cliente = new Cliente(nome, telefone, celular, email);
                ClienteFisico clienteFisico = new ClienteFisico(cpf, rg, orgaoEmissor, estadoEmissor, sexo, nome, telefone, celular, email);
                Endereco endereco = new Endereco(cep, rua, numero, complemento, bairro, cidade, estado);

                Controlador aux = new Controlador();
                aux.cadastrarPessoaFisica(cliente, clienteFisico, endereco);
            }
        } catch (java.lang.NumberFormatException e) {
            numeroIncorreto();
        }
    }

    private void cadastrarPessoaJuridico() {
        try {
            String nome = jtNomeJuridico.getText();
            String cnpj = jtCnpj.getText();
            String nomeDoResponsavel = jtNomeResponsavel.getText();
            String cep = jtCepJuridico.getText();
            String rua = jtEnderecoJuridico.getText();
            int numero = Integer.parseInt(jtNumeroJuridico.getText());
            String complemento = jtComplementoJuridico.getText();
            String bairro = jtBairroJuridico.getText();
            String cidade = jtCidadeJuridico.getText();
            String estado = (String) jcEstadoJuridico.getSelectedItem();
            String telefone = jtTelefoneJuridico.getText();
            String celular = jtCelularJuridico.getText();
            String email = jtEmailJuridico.getText();

            if (nome.equals(null) || nome.equals("")
                    || cnpj.equals(null) || cnpj.equals("")
                    || nomeDoResponsavel.equals(null) || nomeDoResponsavel.equals("")
                    || cep.equals(null) || cep.equals("")
                    || rua.equals(null) || rua.equals("")
                    || numero == 0
                    || complemento.equals(null) || complemento.equals("")
                    || bairro.equals(null) || bairro.equals("")
                    || cidade.equals(null) || cidade.equals("")
                    || telefone.equals(null) || telefone.equals("")
                    || celular.equals(null) || celular.equals("")
                    || email.equals(null) || email.equals("")) {
                semDados();

            } else {

                Cliente cliente = new Cliente(nome, telefone, celular, email);
                ClienteJuridico clienteJuridico = new ClienteJuridico(cnpj, nomeDoResponsavel, nome, telefone, celular, email);
                Endereco endereco = new Endereco(cep, rua, numero, complemento, bairro, cidade, estado);

                Controlador aux = new Controlador();
                aux.cadastrarPessoaJuridica(cliente, clienteJuridico, endereco);
            }
        } catch (java.lang.NumberFormatException e) {
            numeroIncorreto();
        }
    }

    public void semDados() {
        JOptionPane.showMessageDialog(this, "Algum campo vazio!");
    }

    public void numeroIncorreto() {
        JOptionPane.showMessageDialog(this, "O número informado esta incorreto!");
    }

}
